name: parkazoop
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Your added packages
  dio: ^5.4.0
  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.3.0
  shared_preferences: ^2.2.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  # Generator tools
  build_runner: ^2.4.0
  riverpod_generator: ^2.3.0
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
