name: parkazoop
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  dio: ^5.4.0
  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.3.0
  shared_preferences: ^2.2.0
  json_annotation: ^4.9.0
  flutter_svg: ^2.0.9
  http: ^1.2.0   # ðŸ‘ˆ ADD THIS


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.0
  riverpod_generator: ^2.3.0
  json_serializable: ^6.7.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - icons/parkazoop_parking.png

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "icons/parkazoop_parking.png"

